// MilestoneProject/PersistentMilestone/milestone-react/src/components/Ratings.js
import React, { useEffect, useState } from 'react';
import MilestoneService from '../services/MilestoneService';

function Ratings() {
  const [ratings, setRatings] = useState([]);
  const [selectedRating, setSelectedRating] = useState(null);

  useEffect(() => {
    MilestoneService.getAllRatings()
      .then(response => {
        setRatings(response.data);
      })
      .catch(error => {
        console.error("Failed to fetch ratings", error);
      });
  }, []);

  const handleSelectRating = (rating) => {
    setSelectedRating(rating);
  };

  return (
    <div>
      {ratings ? (
        <>
          <h2>Ratings List</h2>
          <ul>
            {ratings.map(rating => (
              <li key={rating.ratingId} onClick={() => handleSelectRating(rating)}>
                Rating ID: {rating.ratingId} - Rating: {rating.rating}
              </li>
            ))}
          </ul>

          {selectedRating && (
            <div>
              <h3>Selected Rating Details</h3>
              <p>Rating ID: {selectedRating.ratingId}</p>
              <p>Ratee ID: {selectedRating.rateeId}</p>
              <p>Rater ID: {selectedRating.raterId}</p>
              <p>Rating: {selectedRating.rating}</p>
              <p>Rating Text: {selectedRating.ratingText}</p>
            </div>
          )}
        </>
      ) : (
        <p>No ratings available</p>
      )}
    </div>
  );
}

export default Ratings;

// MilestoneProject/PersistentMilestone/milestone-angular/src/app/ratings/ratings.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MilestoneServiceService } from '../service/milestone-service.service';
import { Rating } from '../models/Rating';

@Component({
  selector: 'app-list-ratings',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './ratings.component.html',
  styleUrls: ['./ratings.component.css']
})
export class RatingsComponent implements OnInit {
  ratings: Rating[] | null = null;
  selectedRating: Rating | null = null;

  constructor(private service: MilestoneServiceService) { }

  ngOnInit() {
    // Fetch all ratings from the service
    this.service.getAllRatings().subscribe((ratings: Rating[]) => {
      this.ratings = ratings;
    }, error => {
      console.error("Failed to fetch ratings", error);
    });
  }

  onSelectRating(rating: Rating) {
    this.selectedRating = rating;
  }
}


<div *ngIf="ratings">
  <h2>Ratings List</h2>
  <ul>
    <li *ngFor="let rating of ratings" (click)="onSelectRating(rating)">
      Rating ID: {{ rating.ratingId }} - Rating: {{ rating.rating }}
    </li>
  </ul>

  <div *ngIf="selectedRating">
    <h3>Selected Rating Details</h3>
    <p>Rating ID: {{ selectedRating.ratingId }}</p>
    <p>Ratee ID: {{ selectedRating.rateeId }}</p>
    <p>Rater ID: {{ selectedRating.raterId }}</p>
    <p>Rating: {{ selectedRating.rating }}</p>
    <p>Rating Text: {{ selectedRating.ratingText }}</p>
  </div>
</div>

<div *ngIf="!ratings">
  <p>No ratings available</p>
</div>
