// MilestoneProject/PersistentMilestone/milestone-react/src/components/Register.js
import React, { useState } from 'react';
import MilestoneService from '../services/MilestoneService';

const Register = () => {
  const [user, setUser] = useState({
    username: '',
    email: '',
    password: '',
    isAdmin: false
  });

  const [wasSubmitted, setWasSubmitted] = useState(false);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setUser(prev => ({ ...prev, [name]: value }));
  };

  const handleSubmit = (e) => {
    e.preventDefault();

    MilestoneService.registerUser(user)
      .then(response => {
        console.log("Registration successful!", response);
        setWasSubmitted(true);
      })
      .catch(error => {
        console.error("Registration failed.", error);
      });
  };

  return (
    <div className="text-center" style={{ marginLeft: '50px', marginRight: '50px' }}>
      {!wasSubmitted ? (
        <form onSubmit={handleSubmit}>
          <div className="form-group">
            <label htmlFor="username">Username</label>
            <input
              id="username"
              type="text"
              className="form-control"
              placeholder="Enter your username"
              required
              name="username"
              value={user.username}
              onChange={handleChange}
            />
          </div>

          <div className="form-group">
            <label htmlFor="email">Email</label>
            <input
              id="email"
              type="email"
              className="form-control"
              placeholder="Enter your email"
              required
              name="email"
              value={user.email}
              onChange={handleChange}
            />
          </div>

          <div className="form-group">
            <label htmlFor="password">Password</label>
            <input
              id="password"
              type="password"
              className="form-control"
              placeholder="Enter your password"
              required
              name="password"
              value={user.password}
              onChange={handleChange}
            />
          </div>

          <button type="submit" className="btn btn-primary">Register</button>
        </form>
      ) : (
        <div>Registration successful.</div>
      )}
    </div>
  );
};

export default Register;

// MilestoneProject/PersistentMilestone/milestone-angular/src/app/register/register.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MilestoneServiceService } from '../service/milestone-service.service';  // Import the service

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent {
  user = {
    username: '',
    email: '',
    password: '',
    isAdmin: false
  };
  wasSubmitted: boolean = false;

  constructor(private milestoneService: MilestoneServiceService) { } // Inject the MilestoneServiceService

  onSubmit() {
    this.milestoneService.registerUser(this.user).subscribe(response => {
      this.wasSubmitted = true;
      console.log("Registration successful!", response);
    }, error => {
      console.error("Registration failed.", error);
    });
  }
}




<p>Register Works!</p>
<div align="center" style="margin-left:50px;margin-right:50px" *ngIf="!wasSubmitted">
  <form (ngSubmit)="onSubmit()" #registerForm="ngForm">
    <div class="form-group">
      <label for="username">Username</label>
      <input id="username" type="text" class="form-control" placeholder="Enter your username" required
        [(ngModel)]="user.username" name="username">
    </div>
    <div class="form-group">
      <label for="email">Email</label>
      <input id="email" type="email" class="form-control" placeholder="Enter your email" required
        [(ngModel)]="user.email" name="email">
    </div>
    <div class="form-group">
      <label for="password">Password</label>
      <input id="password" type="password" class="form-control" placeholder="Enter your password" required
        [(ngModel)]="user.password" name="password">
    </div>

    <button type="submit" class="btn btn-primary">Register</button>
  </form>
</div>
<div *ngIf="wasSubmitted">
  Registration successful.
</div>
