// MilestoneProject/PersistentMilestone/milestone-angular/src/app/listings/listings.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MilestoneServiceService } from '../service/milestone-service.service';
import { Listing } from '../models/Listing';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-list-listings',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './listings.component.html',
  styleUrls: ['./listings.component.css']
})
export class ListingsComponent implements OnInit {
  listings: Listing[] | null = null;
  selectedListing: Listing | null = null;
  editMode: boolean = false;

  newListing: Listing = {
    artist: '',
    albumTitle: '',
    condition: '',
    imageUrl: '',
    listerId: 0
  };

  constructor(private milestoneService: MilestoneServiceService) { }

  ngOnInit() {
    // Fetch all listings from the service
    this.milestoneService.getAllListings().subscribe((listings: Listing[]) => {
      this.listings = listings;
    }, error => {
      console.error("Failed to fetch listings", error);
    });
  }

  onSelectListing(listing: Listing) {
    this.selectedListing = listing;
  }

  onAddListing() {
    this.milestoneService.createListing(this.newListing).subscribe((response: Listing) => {
      console.log('Listing added successfully', response);
      this.listings?.push(response);
      this.newListing = { artist: '', albumTitle: '', condition: '', imageUrl: '', listerId: 0 };
    }, error => {
      console.error('Failed to add listing', error);
    });
  }

  onDeleteListing(id: string) {
    if (confirm('Are you sure you want to delete this listing?')) {
      this.milestoneService.deleteListing(id).subscribe(() => {
        this.listings = this.listings?.filter(listing => listing.listingId !== Number(id)) || null;
        console.log('Listing deleted successfully');
        this.selectedListing = null;
      }, error => {
        console.error('Failed to delete listing', error);
      });
    }
  }

  onEditListing(listing: Listing) {
    this.selectedListing = listing;
    this.editMode = true;
  }

  onUpdateListing() {
    if (this.selectedListing) {
      const updatedListing: Listing = {
        artist: this.selectedListing.artist,
        albumTitle: this.selectedListing.albumTitle,
        condition: this.selectedListing.condition,
        imageUrl: this.selectedListing.imageUrl,
        listerId: this.selectedListing.listerId
      };

      this.milestoneService.updateListing(this.selectedListing.listingId!.toString(), updatedListing).subscribe((response: Listing) => {
        console.log('Listing updated successfully', response);
        this.editMode = false;
        this.selectedListing = null;
        this.ngOnInit();
      }, error => {
        console.error('Failed to updated listing', error);
      });
    }
  }
}

<p>Listings works!</p>

<div *ngIf="listings">
  <h2>Listings</h2>
  <ul>
    <li *ngFor="let listing of listings" (click)="onSelectListing(listing)">
      Artist: {{ listing.artist }} - Album Title: {{ listing.albumTitle }}
      <button *ngIf="listing.listingId" (click)="onDeleteListing(listing.listingId!.toString())"
        class="btn btn-danger btn-sm">Delete</button>
    </li>
  </ul>

  <!-- Selected Listing Details -->
  <div *ngIf="selectedListing">
    <h3>Selected Listing Details</h3>
    <p>Listing ID: {{ selectedListing.listingId }}</p>
    <p>User ID: {{ selectedListing.listerId }}</p>
    <p>Artist: {{ selectedListing.artist }}</p>
    <p>Album Title: {{ selectedListing.albumTitle }}</p>
    <p>Condition: {{ selectedListing.condition }}</p>
    <img [src]="selectedListing.imageUrl" alt="Album Cover" width="200">

    <!-- Update Listing Form -->
    <h4>Update Listing</h4>
    <form (ngSubmit)="onUpdateListing()" class="needs-validation" novalidate>
      <div class="form-group mb-3">
        <label for="updateArtist" class="form-label">Artist:</label>
        <input id="updateArtist" [(ngModel)]="selectedListing.artist" name="artist" class="form-control" required>
        <div class="invalid-feedback">Artist is required.</div>
      </div>

      <div class="form-group mb-3">
        <label for="updateAlbumTitle" class="form-label">Album Title:</label>
        <input id="updateAlbumTitle" [(ngModel)]="selectedListing.albumTitle" name="albumTitle" class="form-control"
          required>
        <div class="invalid-feedback">Album Title is required.</div>
      </div>

      <div class="form-group mb-3">
        <label for="updateCondition" class="form-label">Condition:</label>
        <input id="updateCondition" [(ngModel)]="selectedListing.condition" name="condition" class="form-control"
          required>
        <div class="invalid-feedback">Condition is required.</div>
      </div>

      <div class="form-group mb-3">
        <label for="updateImageUrl" class="form-label">Image URL:</label>
        <input id="updateImageUrl" [(ngModel)]="selectedListing.imageUrl" name="imageUrl" class="form-control" required>
        <div class="invalid-feedback">Image URL is required.</div>
      </div>

      <button type="submit" class="btn btn-primary">Update Listing</button>
    </form>
  </div>
</div>

<div *ngIf="!listings">
  <p>No listings available</p>
</div>

<!-- Add Listing Form -->
<h3 class="mb-4">Add New Listing</h3>
<form (ngSubmit)="onAddListing()" class="needs-validation" novalidate>
  <div class="form-group mb-3">
    <label for="artist" class="form-label">Artist:</label>
    <input id="artist" [(ngModel)]="newListing.artist" name="artist" class="form-control" required>
    <div class="invalid-feedback">Artist is required.</div>
  </div>

  <div class="form-group mb-3">
    <label for="albumTitle" class="form-label">Album Title:</label>
    <input id="albumTitle" [(ngModel)]="newListing.albumTitle" name="albumTitle" class="form-control" required>
    <div class="invalid-feedback">Album Title is required.</div>
  </div>

  <div class="form-group mb-3">
    <label for="condition" class="form-label">Condition:</label>
    <input id="condition" [(ngModel)]="newListing.condition" name="condition" class="form-control" required>
    <div class="invalid-feedback">Condition is required.</div>
  </div>

  <div class="form-group mb-3">
    <label for="imageUrl" class="form-label">Image URL:</label>
    <input id="imageUrl" [(ngModel)]="newListing.imageUrl" name="imageUrl" class="form-control" required>
    <div class="invalid-feedback">Image URL is required.</div>
  </div>

  <div class="form-group mb-3">
    <label for="listerId" class="form-label">Lister ID:</label>
    <input id="listerId" [(ngModel)]="newListing.listerId" name="listerId" class="form-control" required>
    <div class="invalid-feedback">Lister ID is required.</div>
  </div>

  <button type="submit" class="btn btn-primary">Add Listing</button>
</form>

// MilestoneProject/PersistentMilestone/milestone-react/src/components/Listings.js
import React, { useState, useEffect } from 'react';
import MilestoneService from '../services/MilestoneService';

const Listings = () => {
  const [listings, setListings] = useState([]);
  const [selectedListing, setSelectedListing] = useState(null);
  const [editMode, setEditMode] = useState(false);
  const [newListing, setNewListing] = useState({
    artist: '',
    albumTitle: '',
    condition: '',
    imageUrl: '',
    listerId: 0,
  });

  useEffect(() => {
    MilestoneService.getAllListings().then((response) => {
      setListings(response.data);
    }).catch((error) => {
      console.error('Failed to fetch listings:', error);
    });
  }, []);

  const handleAddListing = () => {
    MilestoneService.createListing(newListing).then((response) => {
      setListings((prevListings) => [...prevListings, response.data]);
      setNewListing({
        artist: '',
        albumTitle: '',
        condition: '',
        imageUrl: '',
        listerId: 0,
      });
    }).catch((error) => {
      console.error('Failed to add listing:', error);
    });
  };

  const handleDeleteListing = (id) => {
    if (!window.confirm('Are you sure you want to delete this listing?')) return;

    MilestoneService.deleteListing(id).then(() => {
      setListings((prevListings) => prevListings.filter((listing) => listing.listingId !== id));
      if (selectedListing?.listingId === id) {
        setSelectedListing(null);
        setEditMode(false);
      }
    }).catch((error) => {
      console.error('Failed to delete listing:', error);
    });
  };

  const handleSelectListing = (listing) => {
    setSelectedListing({ ...listing }); // Make a copy to allow editing
    setEditMode(false);
  };

  const handleEditListing = () => {
    setEditMode(true);
  };

  const handleUpdateListing = () => {
    if (!selectedListing?.listingId) return;

    const id = selectedListing.listingId;

    MilestoneService.updateListing(id, selectedListing).then((response) => {
      setListings((prevListings) =>
        prevListings.map((listing) => (listing.listingId === id ? response.data : listing))
      );
      setEditMode(false);
      setSelectedListing(null);
    }).catch((error) => {
      console.error('Failed to update listing:', error);
    });
  };

  return (
    <div>
      <h2>Listings</h2>

      <ul>
        {listings.map((listing) => (
          <li key={listing.listingId} onClick={() => handleSelectListing(listing)}>
            {listing.artist} - {listing.albumTitle}
            <button
              onClick={(e) => {
                e.stopPropagation();
                handleDeleteListing(listing.listingId);
              }}
              className="btn btn-danger btn-sm ms-2"
            >
              Delete
            </button>
            <button
              onClick={(e) => {
                e.stopPropagation();
                handleSelectListing(listing);
                handleEditListing();
              }}
              className="btn btn-secondary btn-sm ms-2"
            >
              Edit
            </button>
          </li>
        ))}
      </ul>

      <div>
        <h4>Add New Listing</h4>
        <form
          onSubmit={(e) => {
            e.preventDefault();
            handleAddListing();
          }}
        >
          <input
            type="text"
            placeholder="Artist"
            value={newListing.artist}
            onChange={(e) => setNewListing({ ...newListing, artist: e.target.value })}
            className="form-control mb-2"
            required
          />
          <input
            type="text"
            placeholder="Album Title"
            value={newListing.albumTitle}
            onChange={(e) => setNewListing({ ...newListing, albumTitle: e.target.value })}
            className="form-control mb-2"
            required
          />
          <input
            type="text"
            placeholder="Condition"
            value={newListing.condition}
            onChange={(e) => setNewListing({ ...newListing, condition: e.target.value })}
            className="form-control mb-2"
          />
          <input
            type="text"
            placeholder="Image URL"
            value={newListing.imageUrl}
            onChange={(e) => setNewListing({ ...newListing, imageUrl: e.target.value })}
            className="form-control mb-2"
          />
          <input
            type="number"
            placeholder="Lister ID"
            value={newListing.listerId === 0 ? '' : newListing.listerId}
            onChange={(e) => {
              const value = e.target.value;
              setNewListing({
                ...newListing,
                listerId: value === '' ? 0 : parseInt(value)
              });
            }}
            className="form-control mb-2"
            required
          />
          <button type="submit" className="btn btn-primary">Add Listing</button>
        </form>
      </div>

      {selectedListing && (
        <div>
          <h4>{editMode ? 'Edit Listing' : 'Selected Listing Details'}</h4>
          {editMode ? (
            <div>
              <input
                type="text"
                value={selectedListing.artist}
                onChange={(e) => setSelectedListing({ ...selectedListing, artist: e.target.value })}
                className="form-control mb-2"
              />
              <input
                type="text"
                value={selectedListing.albumTitle}
                onChange={(e) => setSelectedListing({ ...selectedListing, albumTitle: e.target.value })}
                className="form-control mb-2"
              />
              <input
                type="text"
                value={selectedListing.condition}
                onChange={(e) => setSelectedListing({ ...selectedListing, condition: e.target.value })}
                className="form-control mb-2"
              />
              <input
                type="text"
                value={selectedListing.imageUrl}
                onChange={(e) => setSelectedListing({ ...selectedListing, imageUrl: e.target.value })}
                className="form-control mb-2"
              />
              <input
                type="number"
                value={selectedListing.listerId}
                onChange={(e) =>
                  setSelectedListing({ ...selectedListing, listerId: parseInt(e.target.value) })
                }
                className="form-control mb-2"
              />
              <button onClick={handleUpdateListing} className="btn btn-success mt-2">Save Changes</button>
            </div>
          ) : (
            <div>
              <p><strong>Artist:</strong> {selectedListing.artist}</p>
              <p><strong>Album Title:</strong> {selectedListing.albumTitle}</p>
              <p><strong>Condition:</strong> {selectedListing.condition}</p>
              <p><strong>Image:</strong> <img src={selectedListing.imageUrl} alt="cover" width="100" /></p>
              <p><strong>Lister ID:</strong> {selectedListing.listerId}</p>
            </div>
          )}
        </div>
      )}
    </div>
  );
};

export default Listings;
