// MilestoneProject/PersistentMilestone/milestone-react/src/components/Login.js
import React, { useState } from 'react';
import MilestoneService from '../services/MilestoneService';

const Login = () => {
  const [credentials, setCredentials] = useState({
    email: '',
    password: ''
  });

  const [wasSubmitted, setWasSubmitted] = useState(false);
  const [token, setToken] = useState('');
  const [username, setUsername] = useState('');

  const handleChange = (e) => {
    const { name, value } = e.target;
    setCredentials(prev => ({ ...prev, [name]: value }));
  };

  const handleSubmit = (e) => {
    e.preventDefault();

    MilestoneService.loginUser(credentials)
      .then(response => {
        console.log("Login successful!", response);
        setWasSubmitted(true);
        setToken(response.data.token);
        setUsername(response.data.user.username);
      })
      .catch(error => {
        console.error("Login failed.", error);
      });
  };

  return (
    <div className="text-center" style={{ marginLeft: '50px', marginRight: '50px' }}>
      {!wasSubmitted ? (
        <form onSubmit={handleSubmit}>
          <div className="form-group">
            <label htmlFor="email">Email</label>
            <input
              id="email"
              type="email"
              className="form-control"
              placeholder="Enter your email"
              required
              name="email"
              value={credentials.email}
              onChange={handleChange}
            />
          </div>

          <div className="form-group">
            <label htmlFor="password">Password</label>
            <input
              id="password"
              type="password"
              className="form-control"
              placeholder="Enter your password"
              required
              name="password"
              value={credentials.password}
              onChange={handleChange}
            />
          </div>

          <button type="submit" className="btn btn-primary">Login</button>
        </form>
      ) : (
        <div>
          Login successful. Your token is <strong>{token}</strong><br />
          Welcome back <strong>{username}</strong>.
        </div>
      )}
    </div>
  );
};

export default Login;

// MilestoneProject/PersistentMilestone/milestone-angular/src/app/login/login.component.ts
import { Component } from '@angular/core';
import { MilestoneServiceService } from '../service/milestone-service.service';  // Import the service
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-login',
  imports: [CommonModule, FormsModule],
  templateUrl: './login.component.html',
  styleUrl: './login.component.css'
})
export class LoginComponent {
  credentials = {
    email: '',
    password: ''
  };
  wasSubmitted: boolean = false;
  token: string = '';
  username: string = '';

  constructor(private milestoneService: MilestoneServiceService) { } // Inject the MilestoneServiceService

  onSubmit() {
    this.milestoneService.loginUser(this.credentials).subscribe(response => {
      this.wasSubmitted = true;
      console.log("Login successful!", response);
      this.token = response.token;
      this.username = response.user.username;
    }, error => {
      console.error("Login failed.", error);
    });
  }
}

<p>login works!</p>
<div align="center" style="margin-left:50px;margin-right:50px" *ngIf="!wasSubmitted">
  <form (ngSubmit)="onSubmit()" #registerForm="ngForm">
    <div class="form-group">
      <label for="email">Email</label>
      <input id="email" type="email" class="form-control" placeholder="Enter your email" required
        [(ngModel)]="credentials.email" name="email">
    </div>
    <div class="form-group">
      <label for="password">Password</label>
      <input id="password" type="password" class="form-control" placeholder="Enter your password" required
        [(ngModel)]="credentials.password" name="password">
    </div>

    <button type="submit" class="btn btn-primary">Login</button>
  </form>
</div>
<div *ngIf="wasSubmitted">
  Login successful. Your token is {{ token }} <br> Welcome back {{ username }}.
</div>
