// MilestoneProject/PersistentMilestone/milestone-react/src/App.js
import { useState } from 'react';
import { BrowserRouter as Router, Routes, Route, Link } from 'react-router-dom';
import Users from './components/Users';
import Listings from './components/Listings';
import Chats from './components/Chats';
import Register from './components/Register';
import Login from './components/Login';
import Ratings from './components/Ratings';
import './App.css';
import 'bootstrap/dist/css/bootstrap.min.css';

function App() {
  const [title] = useState("Vinyl Trader");
  const version = 1.0;

  const displayVersion = (e) => {
    e.preventDefault();
    alert(`Version: ${version}`);
  };

  return (
    <Router>
      <div className="text-center py-4 bg-light">
        <h1>Welcome to {title}</h1>
      </div>

      <nav className="navbar navbar-expand-lg navbar-dark bg-dark">
        <div className="container">
          <Link className="navbar-brand" to="/">Vinyl Record Marketplace</Link>
          <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span className="navbar-toggler-icon"></span>
          </button>
          <div className="collapse navbar-collapse" id="navbarNav">
            <ul className="navbar-nav me-auto">
              <li className="nav-item"><Link className="nav-link" to="/login">Login</Link></li>
              <li className="nav-item"><Link className="nav-link" to="/register">Register</Link></li>
              <li className="nav-item"><Link className="nav-link" to="/users">Users</Link></li>
              <li className="nav-item"><Link className="nav-link" to="/ratings">Ratings</Link></li>
              <li className="nav-item"><Link className="nav-link" to="/listings">Listings</Link></li>
              <li className="nav-item"><Link className="nav-link" to="/chats">Chats</Link></li>
            </ul>
            <ul className="navbar-nav">
              <li className="nav-item">
                <a href="#" className="nav-link" onClick={displayVersion}>About</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

      <div className="container mt-4">
        <Routes>
          <Route path="/" element={<div>Welcome to the Vinyl Record Marketplace</div>} />
          <Route path="/users" element={<Users />} />
          <Route path="/listings" element={<Listings />} />
          <Route path="/chats" element={<Chats />} />
          <Route path="/register" element={<Register />} />
          <Route path="/login" element={<Login />} />
          <Route path="/ratings" element={<Ratings />} />
        </Routes>
      </div>
    </Router>
  );
}

export default App;

// MilestoneProject/PersistentMilestone/milestone-angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterModule, RouterOutlet } from '@angular/router';
import { Router } from '@angular/router';
import { RouterLink } from '@angular/router';
import { ReactiveFormsModule } from '@angular/forms';

@Component({
  selector: 'app-root',
  imports: [RouterOutlet, RouterLink, RouterModule],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  title = 'Vinyl Trader';
  version = 1.0;
  private router: Router;
  displayVersion() {
    alert(this.version);
  };
  displayArtistList() {
    alert("display list here");
  }
  constructor(private r: Router) {
    this.router = r;
  };
}

<div style="text-align:center">
  <h1>
    Welcome to {{ title }}
  </h1>
</div>

<div>
  <nav class="navbar navbar-expand-lg bg-light p-0">
    <div class="container">
      <a class="navbar-brand" href="#">Vinyl Record Marketplace</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item" role="presentation"><a class="nav-link" routerLink="/login">Login</a></li>
          <li class="nav-item" role="presentation"><a class="nav-link" routerLink="/register">Register</a></li>
          <li class="nav-item" role="presentation"><a class="nav-link" routerLink="/users">Users</a></li>
          <li class="nav-item" role="presentation"><a class="nav-link" routerLink="/ratings">Ratings</a></li>
          <li class="nav-item" role="presentation"><a class="nav-link" routerLink="/listings">Listings</a></li>
          <li class="nav-item" role="presentation"><a class="nav-link" routerLink="/chats">Chats</a></li>
          <li class="nav-item"><a class="nav-link" href="" (click)="displayVersion()">About</a></li>
        </ul>
      </div>
    </div>
  </nav>
</div>

<router-outlet></router-outlet>
